### PR TITLE
image crashing fixed

### PR DESCRIPTION
**Pull request by amityadav2026**
# Description

item img when not given crashing fixed

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @amityadav2026, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @amityadav2026! You're now able to merge the PR.

**Comment by amityadav2026** [comment]
Screenshot (67)

**Pull request merged**
